### ISSUE TITLE
Callback must be a function

### ISSUE THREAD

**Issue by liurui39660** [chekun/hexo-uuid#3]
When I new a post, it throws an error with the following message:

```
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:127:9)
    at Object.writeFile (fs.js:1123:14)
    at Hexo.module.exports (E:\Blog\node_modules\hexo-uuid\lib\hexo-uuid.js:18:8)
    at Hexo.emit (events.js:182:13)
    at Promise.all.then (E:\Blog\node_modules\hexo\lib\hexo\post.js:55:11)
    at tryCatcher (E:\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\Blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (E:\Blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (E:\Blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (E:\Blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (E:\Blog\node_modules\bluebird\js\release\promise.js:638:18)
    at PromiseArray._resolve (E:\Blog\node_modules\bluebird\js\release\promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (E:\Blog\node_modules\bluebird\js\release\promise_array.js:144:14)
    at Promise._settlePromise (E:\Blog\node_modules\bluebird\js\release\promise.js:574:26)
    at Promise._settlePromise0 (E:\Blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (E:\Blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (E:\Blog\node_modules\bluebird\js\release\promise.js:638:18)
    at E:\Blog\node_modules\bluebird\js\release\nodeback.js:42:21
    at E:\Blog\node_modules\graceful-fs\graceful-fs.js:99:16
    at E:\Blog\node_modules\graceful-fs\graceful-fs.js:43:10
    at C:\Users\liurui\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:139:20)
```

where `E:\Blog\` is the blog directory, and the username is `liurui`.

I'm using node.js v10.9.0, npm 6.2.0, Windows 10

The npm package installed are (a.k.a. output of `npm ls --depth=0`):

```
hexo-site@0.0.0 E:\Blog
+-- hexo@3.7.1
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-index@0.2.1
+-- hexo-generator-sitemap@1.2.0
+-- hexo-generator-tag@0.2.0
+-- hexo-inject@1.0.0
+-- hexo-math@3.0.4
+-- hexo-pdf@1.1.1
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.2
+-- hexo-renderer-stylus@0.3.3
+-- hexo-server@0.3.3
`-- hexo-uuid@1.0.1
```

I tried to add an empty function to the line 18, hexo-uuid.js, like this:

```js
'use strict';

const uuid = require('uuid');
const fs = require('fs');

module.exports = (post) => {

  let lines = post.content.split('\n');
  let index = lines.findIndex(item => item === 'uuid:');
  if (index > -1) {
    lines[index] += (' ' + uuid.v1());
  } else {
    lines.splice(1, 0, 'uuid: ' + uuid.v1());
  }

  post.content = lines.join('\n');
  if (post.path !== false) {
    fs.writeFile(post.path, post.content, ()=>null);
  }

};
```

It works without any error or warning, but I don't think it is not the best solution
However, I'm not familiar with JavaScript, thus maybe I can't open a pull request.
Please fix this problem.

**Comment by chekun** [comment]
Fixed by passing an empty callback 👍
